### ISSUE TITLE
BaseLearner method _evaluate missed the increment attribute

### ISSUE THREAD

**Issue by wujunnan0929** [zhoudw-zdw/CIL_Survey#3]
My advice code for "base.py":

```
self._increment = args["increment"]
  
def _evaluate(self, y_pred, y_true):
      ret = {}
      grouped = accuracy(y_pred.T[0], y_true, self._known_classes, self._increment)
```

**Comment by wujunnan0929** [comment]
The Baselearner class in file "base.py" missed the self._increment attribute at __init__() function.  This bug will cause mistake when call "_evaluate" function. So I recommend to add a line code `self._increment = args["increment"]` at the top of __init__() function.

**Comment by zhoudw-zdw** [comment]
Hi, you can modify the code by passing args["increment"] to self._increment. Besides, we mainly focus on the accuracy among all seen classes. Hence, grouped accuracy is not directly used in this repo/survey.
