### ISSUE TITLE
How to draw pictures in resources folder？

### ISSUE THREAD

**Issue by deer1025** [zhoudw-zdw/CIL_Survey#6]
Sorry. How do I draw the result graph in the resources folder? I can't find the corresponding code.
![image](https://github.com/user-attachments/assets/72987a0a-5a5e-4c86-8e9f-dc86fc65ad73)

**Comment by zhoudw-zdw** [comment]
You should run the code, get the performance curve. Afterward, draw images with https://matplotlib.org/
