### ISSUE TITLE
Bugs in Der and Foster?

### ISSUE THREAD

**Issue by Deexaa** [zhoudw-zdw/CIL_Survey#7]
Thanks for your sharing!
I'd be grateful if you could help me with the bug when reproducing the der.json & foster.json on VTab.

Details belike:
File "LAMDA-PILOT-main/models/base.py", line 260, in _construct_exemplar
    i = np.argmin(np.sqrt(np.sum((class_mean - mu_p) ** 2, axis=1)))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "envs/pilot/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 1325, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pilot/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: attempt to get argmin of an empty sequence

**Comment by zhoudw-zdw** [comment]
It seems that you are not running this repo...

**Comment by Deexaa** [comment]
oh sorry, my mistake.
thank u!!!
