### ISSUE TITLE
Running with my own datasets

### ISSUE THREAD

**Issue by Unbi03** [zhoudw-zdw/CIL_Survey#8]
I appreciate for your contribution!
I'd like to ask about checkpoints, which you shared through google drive.
While editing your code for my own dataset, I found I also need cpts which fits on my environment. But I have only imagenet and cifar...
Could you share the method for making cpts as like you provided ones?
Thank you

**Comment by zhoudw-zdw** [comment]
Thank you for your interest in our work.

You need to save the model after the first incremental stage if you prepare the cpt for your dataset.

However, we recommend training from scratch if you are unfamiliar with pytorch.

**Comment by Unbi03** [comment]
With your instruction, finally it is working in my dataset. Thank you again!
